version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/KDT_BE7_Mini-Project
permissions:
  - object: /home/ec2-user/KDT_BE7_Mini-Project/
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
