#version: 0.0
#os: linux
#
#files:
#  - source: /
#    destination: /home/ubuntu/KDT_BE7_Mini-Project
#permissions:
#  - object: /home/ubuntu/KDT_BE7_Mini-Project/
#    owner: ubuntu
#    group: ubuntu
#hooks:
#  AfterInstall:
#    - location: scripts/deploy.sh
#      timeout: 60
#      runas: ubuntu
