server:
  port: 8080

spring:
  profiles:
    default: dev
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show_sql: true
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: true
    open-in-view: false

## swagger api 설정
springdoc:
  api-docs:
    version: openapi_3_0
    path: /public-api/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /public-api/swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match:
    - /**

jwt:
  access-token:
    secret-key: bab2ee005bf1daad5c736636d8b40184520f49df5d1b3303d923137af0b1dc95
    access-expired: 600000

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/minidb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://15.164.19.60:3306/minidb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: user
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update


