#logging:
#  file:
#    name: myapp.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: myapp.%d{yyyy-MM-dd}-%i.log
#      max-file-size: 10KB
#  pattern:
#    dateformat: Asia/Seoul

spring:
  profiles:
    default: dev
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show_sql: true
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: true
    open-in-view: false

## swagger api 설정
springdoc:
  api-docs:
    version: openapi_3_0
    path: /public-api/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /public-api/swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match:
    - /**

jwt:
  access-token:
    secret-key: bab2ee005bf1daad5c736636d8b40184520f49df5d1b3303d923137af0b1dc95
    access-expired: 600000

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb

---
logging:
  file:
    name: /var/log/myapp.log
  logback:
    rollingpolicy:
      file-name-pattern: myapp.%d{yyyy-MM-dd}-%i.log
      max-file-size: 10KB
  pattern:
    dateformat: Asia/Seoul

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://15.164.19.60:3306/minidb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: user
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


