version: '3'
services:
  accommodation-dev1:
    container_name: accommodation-dev1
    image: woohahalife/accommodation-backend
    ports:
      - "8082:8081"
    networks:
      - backend-network

  accommodation-dev2:
    container_name: accommodation-dev2
    image: woohahalife/accommodation-backend
    ports:
      - "8083:8081"
    networks:
      - backend-network

networks:
  backend-network:
    external: true
