name: Backend Server Deploy to AWS EC2 and Docker

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build and Test with Gradle
        run: ./gradlew clean build -x test
        shell: bash

      - name: Build docker image
        run: docker build -t woohahalife/accommodation-backend .

      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: woohahalife
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to docker hub
        run: docker push woohahalife/accommodation-backend .

      - name: Connect to AWS & Execute Application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker stop $(docker ps -a -q) 
            docker rm $(docker ps -a -q) 
            docker pull woohahalife/accommodation-backend
            docker run -d -p 8081:8081 --name accommodation-backend woohahalife/accommodation-backend